DROP database stampee;

-- MySQL Script generated by MySQL Workbench
-- Wed Dec 10 01:12:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stampee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stampee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stampee` DEFAULT CHARACTER SET utf8 ;
USE `stampee` ;

-- -----------------------------------------------------
-- Table `stampee`.`condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`condition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`pays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`ville` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`privilege` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `nom_utilisateur` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `code_postal` VARCHAR(45) NOT NULL,
  `courriel` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(25) NOT NULL,
  `pays_id` INT NOT NULL,
  `ville_id` INT NOT NULL,
  `privilege_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_utilisateur_pays1_idx` (`pays_id` ASC) VISIBLE,
  INDEX `fk_utilisateur_ville1_idx` (`ville_id` ASC) VISIBLE,
  INDEX `fk_utilisateur_privilege1_idx` (`privilege_id` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_pays1`
    FOREIGN KEY (`pays_id`)
    REFERENCES `stampee`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_ville1`
    FOREIGN KEY (`ville_id`)
    REFERENCES `stampee`.`ville` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_privilege1`
    FOREIGN KEY (`privilege_id`)
    REFERENCES `stampee`.`privilege` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`couleur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`couleur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`timbre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`timbre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `tirage` VARCHAR(45) NOT NULL,
  `dimension` INT NOT NULL,
  `certifie` BIT(8) NOT NULL,
  `condition_id` INT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  `couleur_id` INT NOT NULL,
  `pays_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_timbre_condition1_idx` (`condition_id` ASC) VISIBLE,
  INDEX `fk_timbre_utilisateur1_idx` (`utilisateur_id` ASC) VISIBLE,
  INDEX `fk_timbre_couleur1_idx` (`couleur_id` ASC) VISIBLE,
  INDEX `fk_timbre_pays1_idx` (`pays_id` ASC) VISIBLE,
  CONSTRAINT `fk_timbre_condition1`
    FOREIGN KEY (`condition_id`)
    REFERENCES `stampee`.`condition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timbre_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `stampee`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timbre_couleur1`
    FOREIGN KEY (`couleur_id`)
    REFERENCES `stampee`.`couleur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timbre_pays1`
    FOREIGN KEY (`pays_id`)
    REFERENCES `stampee`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`enchere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`enchere` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prix_plancher` INT NOT NULL,
  `valeur_estimee` INT NOT NULL,
  `coups` BIT(8) NOT NULL,
  `debut` DATE NOT NULL,
  `fin` DATE NOT NULL,
  `timbre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enchere_timbre1_idx` (`timbre_id` ASC) VISIBLE,
  CONSTRAINT `fk_enchere_timbre1`
    FOREIGN KEY (`timbre_id`)
    REFERENCES `stampee`.`timbre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(75) NOT NULL,
  `timbre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_timbre1_idx` (`timbre_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_timbre1`
    FOREIGN KEY (`timbre_id`)
    REFERENCES `stampee`.`timbre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`mise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`mise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valeur` INT NOT NULL,
  `date` TIMESTAMP(6) NOT NULL,
  `enchere_id` INT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mise_enchere1_idx` (`enchere_id` ASC) VISIBLE,
  INDEX `fk_mise_utilisateur1_idx` (`utilisateur_id` ASC) VISIBLE,
  CONSTRAINT `fk_mise_enchere1`
    FOREIGN KEY (`enchere_id`)
    REFERENCES `stampee`.`enchere` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mise_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `stampee`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO privilege (nom) VALUES('Lord');
INSERT INTO privilege (nom) VALUES ('Client');
INSERT INTO stampee.condition (nom) VALUES('Parfaite');
INSERT INTO stampee.condition (nom) VALUES ('Excellente');
INSERT INTO stampee.condition (nom) VALUES('Bonne');
INSERT INTO stampee.condition (nom) VALUES ('Moyenne');
INSERT INTO stampee.condition (nom) VALUES('Endommagé');

SELECT * FROM utilisateur;
SELECT * FROM timbre;
SELECT * FROM pays;
SELECT * FROM ville;
SELECT * FROM stampee.condition;
SELECT * FROM couleur;
SELECT * FROM enchere;
SELECT * FROM mise;